language: java
sudo: required
services:                                      
  - docker
before_install:
  - cd coralwatch-webapp
after_success:
  - ./build_docker.sh
  - sudo docker save coralwatch > coralwatch.docker
before_deploy:
  - xz --verbose coralwatch.docker
  - curl -sOL https://github.com/uq-eresearch/backup2swift/releases/download/0.1.1/backup2swift
  - chmod +x backup2swift
  - openssl aes-256-cbc -K $encrypted_d2b4cbe3dd39_key -iv $encrypted_d2b4cbe3dd39_iv -in ../container-upload.json.enc -out container-upload.json -d
deploy:
  provider: script
  script: ../deploy_to_container.sh
  skip_cleanup: true
  on:
    branch: travis-ci