<h3>Coral Bleaching Graphs Explained</h3>
<p>
    CoralWatch uses data entered into the website to generate bar graphs showing colour
    score changes over time for specific reefs. The x-axis (horizontal) shows time in
    months. The y-axis (vertical) shows the average colour score for every coral examined
    on that reef during that month. Please note no bar will be generated if data was
    not entered for that reef during that month.
</p>
<p>
    The colour score ranges from 1 to 6 with 1 representing the brightest corals and
    6 representing the darkest. It is important to note that not every coral will reach
    a score of 6, for example the darkest colour observed in some species is a 4. For
    this reason, you need to analyse grouped data rather than looking at a single coral
    at a single point in time. For example, you can analyse changes to colour score
    over time (as provided in the graphs generated by this website) or 'fingerprint'
    graphs (directly below).
</p>
<p>

    The graphs generated by this website show how a particular reef changes over time.
    These graphs provide an indication of the condition of many different reefs at many
    different times.
</p>
<p>
    Please note the graphs produced by this website are neither exhaustive nor exclusive.
    There are many other types of graphs that can be produced and we encourage you to
    explore different options. The following graphs are examples of graphs you can create
    using Microsoft Excel. For information about generating graphs in a classroom setting
    please refer to the 'Education Package' link in the main menu.
</p>
<h3>
    Fingerprinting different reefs
</h3>
<img src="${baseUrl}/images/graph_fingerprinting.jpg" alt="Fingerprinting different reefs"/>
<br/>
<p>
    The above graphs show the distribution of the colours of 100 randomly selected corals
    during and after the 2002 mass bleaching event on the Great Barrier Reef, Australia.
    They provide a 'fingerprint' for a reef at a certain point in time, with the distribution
    reflecting the condition of the reef.
</p>
<p>
    A healthy reef generally has a majority of corals with scores over 3, a few corals
    with scores of 2 and a very small number of corals with a colour score of 1 (right
    graph). Whereas a bleached reef generally has a majority of corals with a score
    of 1 and a few corals with a core of 2 or 3 (left graph). Your analysis will be
    enhanced if you're able to collect data all year round and hence determine a baseline
    for your reef.
</p>
<h3>
    Repeated measurements of specific colonies
</h3>
<img src="${baseUrl}/images/graph_gatherData.jpg" alt="Repeated measurements of specific colonies "/>
<br/>
<br/>
<p>
    The above graph shows colour chart measurements from 20 marked corals on Heron Island,
    Australia. Corals that showed signs of bleaching in March 2002 had significantly
    lighter colours than corals that were not affected. From May onwards there was no
    significant difference between the two groups. In early September a rainstorm coincided
    with a low tide and resulted in bleaching of both, previously healthy and bleached
    colonies.
</p>